engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
checks:
  import/extensions:
    enabled: false
ratings:
  paths:
  - "server/*.js"
  - "server/**/*.js"
exclude_paths:
  - "server/tests/"
  - "server/models/"
  - "server/seeders/"
  - "migrations/"
  - "node_modules/"
  - "client/materialize/"
  - "client/test/"
  - "server/public/"
  - "examples/"
  - "client/sass/"
  - "client/font-awesome/"
