engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "server/*.js"
  - "server/**/*.js"
exclude_paths:
  - "server/tests/"
  - "server/models/"
  - "server/seeders/"
  - "migrations/"
  - "node_modules/"
  - "client/src/materialize/"
  - "client/test/"
  - "server/public/"
  - "examples/"
  - "client/src/sass/"
  - "client/src/font-awesome/"
